version: '2'
services:

  db:
    image: mysql
    container_name: set-date-mysql
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d/
    ports:
      - 13306:3306
    env_file: .env

  web:
    container_name: set-date-rails
    build: .
    command: /bin/sh -c "rm -f /set-date/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/set-date
    ports:
      - "3000:3000"
    depends_on:
      - db
